# Linear Algebra in Cryptography

### Cryptography is the study of the teachniques of writing and decoding messages in code.

### Cipher - a procedure that will render a message unintelligible to the recipient. Used to alse recreate teh original text.

### Plaintext - the message or information that is being encrypted.

### Ciphertext - the message or information that is created after the cipher has been used.

In [1]:
import numpy as np

In [2]:
# Matrix that is used for encrypting and decrypting a message must be invertible.
def is_invertible(matrix):
    # Check if the matrix is square
    if matrix.shape[0] != matrix.shape[1]:
        return False

    # Try to compute the determinant
    try:
        np.linalg.inv(matrix)
        return True
    except np.linalg.LinAlgError:
        return False

In [3]:
matrix = np.array([[-3, -3, -4], [0, 1, 1], [4, 3, 4]])
print(is_invertible(matrix))

True


## Encrypting

In [4]:
# Step 1: Optain an cipher matrix that is invertible
cipher_matrix = np.array([[-3, -3, -4], [0, 1, 1], [4, 3, 4]])

In [5]:
# Step 2: Obtain a plaintext that will need to be dectrypted
text = "The quick brown fox jumps over the lazy dog"

In [6]:
# Step 3: Replace each letter with its numerical representation and replace space with 27
k = []
for i in text:
    k.append("abcdefghijklmnopqrstuvwxyz ".index(i.lower()) + 1)
print(text)
print(k)

The quick brown fox jumps over the lazy dog
[20, 8, 5, 27, 17, 21, 9, 3, 11, 27, 2, 18, 15, 23, 14, 27, 6, 15, 24, 27, 10, 21, 13, 16, 19, 27, 15, 22, 5, 18, 27, 20, 8, 5, 27, 12, 1, 26, 25, 27, 4, 15, 7]


In [7]:
# Step 4: Separate these values into vectors, so that the number of rows of each vector is equivalent to the number of rows of the cipher matrix.
# Values are placed into each vector one at a time, going down a row for each value. Once a vector is filled the next vector is created. If the last
# vector does not get filled by the plaintext then the remaining entries will hold the value for a space.
plaintext_matrix = [[] for _ in range(len(cipher_matrix))]
r = 0
for i in k:
    plaintext_matrix[r].append(i)
    r = (r + 1) % len(cipher_matrix)

for i in range(len(cipher_matrix) - 1):
    if len(plaintext_matrix[i]) != len(plaintext_matrix[i+1]): plaintext_matrix[i+1].append(27)

plaintext_matrix

[[20, 27, 9, 27, 15, 27, 24, 21, 19, 22, 27, 5, 1, 27, 7],
 [8, 17, 3, 2, 23, 6, 27, 13, 27, 5, 20, 27, 26, 4, 27],
 [5, 21, 11, 18, 14, 15, 10, 16, 15, 18, 8, 12, 25, 15, 27]]

In [8]:
# Step 5: Multiply cipher matrix and plaintext_matrix to obtain encrypted matrix.
encrypted_matrix = np.dot(cipher_matrix, plaintext_matrix)
encrypted_matrix

array([[-104, -216,  -80, -159, -170, -159, -193, -166, -198, -153, -173,
        -144, -181, -153, -210],
       [  13,   38,   14,   20,   37,   21,   37,   29,   42,   23,   28,
          39,   51,   19,   54],
       [ 124,  243,   89,  186,  185,  186,  217,  187,  217,  175,  200,
         149,  182,  180,  217]])

## Decrypting

In [9]:
# Step 1: Obtain a reverse of the cipher_matrix
cipher_matrix_inverse = np.linalg.inv(cipher_matrix)

cipher_matrix_inverse

array([[ 1.,  0.,  1.],
       [ 4.,  4.,  3.],
       [-4., -3., -3.]])

In [10]:
# Step 2: Obtain plaintext_matrix by multiplying cipher_matrix_inverse and encrypted_matrix
plaintext_matrix = np.dot(cipher_matrix_inverse, encrypted_matrix)
print(plaintext_matrix)

[[20. 27.  9. 27. 15. 27. 24. 21. 19. 22. 27.  5.  1. 27.  7.]
 [ 8. 17.  3.  2. 23.  6. 27. 13. 27.  5. 20. 27. 26.  4. 27.]
 [ 5. 21. 11. 18. 14. 15. 10. 16. 15. 18.  8. 12. 25. 15. 27.]]


In [11]:
# Step 3: Obtain plaintext by replacing numbers by the letter that they represent and concatinating them back together
plaintext_matrix2 = [[None for _ in range(len(plaintext_matrix[0]))] for _ in range(len(plaintext_matrix))]
for i in range(len(plaintext_matrix)):
    for j in range(len(plaintext_matrix[i])):        
        plaintext_matrix2[i][j] = "abcdefghijklmnopqrstuvwxyz "[int(plaintext_matrix[i][j])-1]

plaintext = ""
for i in range(len(plaintext_matrix) * len(plaintext_matrix[0])):
    plaintext += plaintext_matrix2[i % 3][i // 3]
print(plaintext)

the quick brown fox jumps over the lazy dog  
